# Generated by Django 3.1.5 on 2021-01-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(related_name='posts', to='mona.Image'),
        ),
    ]
