# Generated by Django 3.1.5 on 2021-01-11 01:34

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mona', '0002_auto_20210111_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
    ]
