# Generated by Django 3.1.5 on 2021-01-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mona', '0005_image_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
